CREATE TABLE IF NOT EXISTS TABLE_NAME (
    conversation_id VARCHAR(36) NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL')),
    "timestamp" TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS TABLE_NAME_CONVERSATION_ID_TIMESTAMP_IDX
ON TABLE_NAME(conversation_id, "timestamp");