spring.application.name=ch01-spring-ai-project

server.port=8081
# Enable ANSI output in the console
spring.output.ansi.enabled=ALWAYS

logging.charset.console=%clr[blue]UTF-8 %clr(%logger.%M\\(%F:%L)) - %clr(%msg%n){faint}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true
spring.web.resources.cache.cachecontrol.max-age=0


spring.ai.openai.api-key=${OPENAI_API_KEY}
